### ISSUE TITLE
https://www.ayushman-sinha.me/coding stays stuck at `Loading...`

### ISSUE THREAD

**Issue by hirehamir** [ayushman-sinha/ayushman_sinha#1]

**Comment by hirehamir** [comment]
[Screencast from 03-07-2024 02:01:14 AM.webm](https://github.com/ayushman-sinha/ayushman_sinha/assets/43425812/9b8539d1-2cf6-4787-91e6-8de42e3543e8)

**Comment by ayushman-sinha** [comment]
Thanks for bringing out the issue to my notice. The response object for the codeforces API was changed due to which it could not be displayed correctly. There was some issues with the axios also which is fixed by using fetch API instead in the backend. Leetcode graph is being displayed currently, Codeforces graph will be fixed soon.
![image](https://github.com/ayushman-sinha/ayushman_sinha/assets/77104799/0b3d9889-689b-4ccd-b08d-2ad0a56cec18)
